### PR TITLE
Feature/homepage

### PR DESCRIPTION
**Pull request by SpartanDeBoss**
# Description
Created Index Page.
Please provide a short summary explaining what this PR is about.
In this PR an index.jsx file is created with an input, submit button, and Create New Team. without any further css applied. 

Fixes # (issue)
* The next Pages linked to Submit and Create New Team are not created yet. so it not working as intended but we are working on those.
 
# How to test?
*You can test it by running npm start. 

#Please provide a short summary of how your changes can be tested.
*Right now when u run the code and you click on the * Create new team. it navigates to a new page Page not found. As said above we need to link some of the pages to get to work better.

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [ ] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [ ] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [ ] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by naresh699 — APPROVED** [review]
Approving. One query :  don't we need any CSS for this app

**Review by naresh699 — COMMENTED** [review]
seem like node version is outdated. Please check it should be 18+ version

**Comment by shpomp** [comment]
https://github.com/HackYourFuture-CPH/team26-checkin/pull/2/commits/f1c9a3683419fc9f8911bbcc60413a401e02e4f0

**Comment by SpartanDeBoss** [comment]
> seem like node version is outdated. Please check it should be 18+ version

I updated but for some reason, it seems it failing with the build when u check node -v it says
v21.7.1

**Comment by SpartanDeBoss** [comment]
> Approving. One query : don't we need any CSS for this app

the plan was to do the styling after easter,  just to focus on getting the pages set up first.

**Pull request merged**
